In [1]:
import numpy as np


In [2]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [3]:
mean_a = a.mean(axis = 0)
mean_a

array([ 2. ,  8.4])

In [4]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

№3

In [18]:
b = a_centered.T[0]
b

array([-1.,  0.,  1.,  1., -1.])

In [19]:
c = a_centered.T[1]
c

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [20]:
 a_centered_sp = b@c
 a_centered_sp

8.0

In [21]:
 a_centered_sp / 4

2.0

№4

In [ ]:
np.cov(a.T)[0, 1]